### ISSUE TITLE
vitables installation problem

### ISSUE THREAD

**Issue by uvemas** [conda-forge/vitables-feedstock#1]
Hi,
the qtpy dependency is giving installation problems to some users (see https://github.com/uvemas/ViTables/issues/75). I haven't experienced the problem when installing directly the package, but if a vitables environment is created first and then the package is installed then the problem appears. Would it be possible to add this dependency to the meta.yaml file and see if it fixes the problem?

Thanks

**Comment by rth** [comment]
For my part, on linux this conda-forge package fails to run in a clean conda virtualenv for all supported Python versions,
  * with Python 2.7,
     ```
     conda create -c conda-forge -n vitables27 ViTables==3.0.0 python=2.7
     source activate vitables2.7
     vitables
     ```
     fails with,
     ```
     pkg_resources.DistributionNotFound: The 'PyQt5>=5.5.1' distribution was not found and is required by ViTables
     ```
     where PyQt5.6.0 was pulled by conda; previously reported in https://github.com/uvemas/ViTables/issues/79
  * With Python 3.5 and 3.6,
     ```
     conda create -c conda-forge -n vitables3.5 ViTables==3.0.0 python=2.7
     source activate vitables3.5
     vitables
     ```
     fails with,
     ```
     pkg_resources.DistributionNotFound: The 'ViTables==3.0.0' distribution was not found and is required by the application
     ```
     previously reported in https://github.com/uvemas/ViTables/issues/74

**Comment by uvemas** [comment]
Hi @rth. As you know many people have problems with the conda-forge package, but the same manual workaround that work for them should work for you too. If it is not the case then I don't know how to help you, sorry :-( What I'm trying to do in [#3](https://github.com/conda-forge/vitables-feedstock/issues/3) is to make the workaround automatically applied when the package is installed. It is not the perfect solution but I think it is an improvement.

**Comment by rth** [comment]
@uvemas Last time I used vitables was around 2014 and I'm quite happy it still exists and is working now. Thank you for maintaining and developing it all these years!

> As you know many people have problems with the conda-forge package, but the same manual workaround that work for them should work for you too. If it is not the case then I don't know how to help you, sorry :-(

I did see that on the issue tracker, and my point was that this conda-forge package appears a bit broken.  As a result, I think it might be easier to fix it here, rather than suggesting to users [in the FAQ](http://vitables.org/Docs/faq.html#can-i-use-vitables-with-anaconda3) that they manually apply some patches for conda. I know your proposed approach in #3 will fix https://github.com/uvemas/ViTables/issues/79 but it still doesn't address the above installation problem for Python >=3.5. 

Essentially I think the root cause of this issues is that the install with conda is doubly constrained. The dependencies versions are not specified in `recipe/meta.yaml` but then they are specified in the `setup.py` which results in the insatisfied requirements issues. For instance, if I create a virtualenv with all the dependencies,
```py
conda create -n vitables-new qtpy pyqt numpy numexpr pytables  python=3.6
source activate vitables-new
```
then download vitables 3.0.0 from the github tag, remove the requirements line from the `setup.py` and install it - everything work fine. 

So will propose a PR to patch  `setup.py` at the build time here  which should also fix #3, unless @scopatz has a better idea... )

**Comment by uvemas** [comment]
I agree with you, it is better to fix this problem on the conda side. Unfortunately conda packages are not my field. Anyway, if I can help somehow just tell me.

**Comment by mivade** [comment]
I haven't tested it thoroughly yet, but a quick and dirty workaround might be to use pip to build the package instead of setup.py since pip provides an option to ignore dependencies:

```
pip install --no-deps .
```

**Comment by rth** [comment]
Thanks, @mivade that will be certainly easier than patching `setup.py` will try that in the PR above.
